name: "Dagger Version"
description: "Get the required Dagger version from dagger.json"
branding:
  icon: "tag"
  color: "blue"

inputs:
  path:
    description: "Path to the directory containing dagger.json (defaults to repository root)"
    required: false
    default: ""
  github-token:
    description: "GitHub token for API access"
    required: false
    default: ${{ github.token }}

runs:
  using: "node16"
  main: "dist/index.js"
