name: Test Dagger Version Action

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Test without path parameter (default behavior)
          - repository: 'dagger/registry-redirect'
          # Test with path parameter
          - repository: 'dagger/agents'
            path: 'melvin'

    steps:
      # Checkout the action repository
      - name: Checkout dagger-version-action
        uses: actions/checkout@v4

      # Test API access without checkout (no path)
      - name: Test API access (no checkout, no path)
        id: dagger_version_api_no_path
        if: ${{ !matrix.path }}
        uses: ./
        env:
          GITHUB_REPOSITORY: ${{ matrix.repository }}
          GITHUB_REF: refs/heads/main

      # Test API access without checkout (with path)
      - name: Test API access (no checkout, with path)
        id: dagger_version_api_with_path
        if: ${{ matrix.path }}
        uses: ./
        with:
          path: ${{ matrix.path }}
        env:
          GITHUB_REPOSITORY: ${{ matrix.repository }}
          GITHUB_REF: refs/heads/main

      # Display API results
      - name: Display API result
        run: |
          if [ -n "${PATH_PARAM}" ]; then
            echo "Dagger version (API access): ${{ steps.dagger_version_api_with_path.outputs.version }}"
          else
            echo "Dagger version (API access): ${{ steps.dagger_version_api_no_path.outputs.version }}"
          fi
        env:
          PATH_PARAM: ${{ matrix.path }}
