name: Test Dagger Version Action

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Test without path parameter (default behavior)
          - repository: 'dagger/registry-redirect'
          # Test with path parameter
          - repository: 'dagger/agents'
            path: 'melvin'

    steps:
      - name: Checkout dagger-version-action
        uses: actions/checkout@v4

      # Test without checkout (using API) - without path parameter
      - name: Test API access (no checkout, no path)
        id: dagger_version_api_no_path
        if: matrix.path == null
        uses: ./
        with:
          repository: ${{ matrix.repository }}

      # Test without checkout (using API) - with path parameter
      - name: Test API access (no checkout, with path)
        id: dagger_version_api_with_path
        if: matrix.path != null
        uses: ./
        with:
          repository: ${{ matrix.repository }}
          path: ${{ matrix.path }}

      - name: Display API result
        run: |
          echo "Repository: ${{ matrix.repository }}${{ matrix.path != null && format(', Path: {0}', matrix.path) || ' (default path)' }}"
          if [ "${{ matrix.path != null }}" == "true" ]; then
            echo "Dagger version (API access): ${{ steps.dagger_version_api_with_path.outputs.version }}"
          else
            echo "Dagger version (API access): ${{ steps.dagger_version_api_no_path.outputs.version }}"
          fi

      # Test with checkout
      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repository }}
          path: test-repo

      # Test with checkout - without path parameter
      - name: Test with checkout (no path)
        id: dagger_version_checkout_no_path
        if: matrix.path == null
        uses: ./
        with:
          path: test-repo

      # Test with checkout - with path parameter
      - name: Test with checkout (with path)
        id: dagger_version_checkout_with_path
        if: matrix.path != null
        uses: ./
        with:
          path: test-repo/${{ matrix.path }}

      - name: Display checkout result
        run: |
          echo "Repository: ${{ matrix.repository }}${{ matrix.path != null && format(', Path: {0}', matrix.path) || ' (default path)' }}"
          if [ "${{ matrix.path != null }}" == "true" ]; then
            echo "Dagger version (with checkout): ${{ steps.dagger_version_checkout_with_path.outputs.version }}"
          else
            echo "Dagger version (with checkout): ${{ steps.dagger_version_checkout_no_path.outputs.version }}"
          fi
