name: Test Dagger Version Action

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-with-checkout:
    name: Test with ${{ matrix.repository }}${{ matrix.path && format(' (Path: {0})', matrix.path) || '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - repository: 'dagger/registry-redirect'
          - repository: 'dagger/agents'
            path: 'melvin'
    
    steps:
      # Checkout the action's code
      - name: Checkout action code
        uses: actions/checkout@v4
        with:
          path: 'action'
      
      # Checkout the target repository
      - name: Checkout ${{ matrix.repository }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repository }}
          path: 'target-repo'
      
      # Test with path parameter
      - name: Test with path parameter
        id: test_path
        uses: ./action
        with:
          path: target-repo${{ matrix.path && format('/{0}', matrix.path) || '' }}
      
      # Display result
      - name: Display test results
        run: |
          REPO="${{ matrix.repository }}"
          PATH_INFO="${{ matrix.path && format(' (Path: {0})', matrix.path) || '' }}"
          VERSION="${{ steps.test_path.outputs.version }}"
          
          echo "Repository: $REPO$PATH_INFO"
          echo "Dagger version: $VERSION"
          
          # Validate that we got a version
          if [ -z "$VERSION" ]; then
            echo "Error: No version was returned"
            exit 1
          fi
